const char *cifar_superclasses[20] = {"aquatic mammals",
										"fish",
										"flowers",
										"food containers",
										"fruit and veget.",
										"electr. devices",
										"furniture",
										"insects",
										"carnivores",
										"outdoor things",
										"outdoor scenes",
										"large animals",
										"medium mammals",
										"invertebrates",
										"people",
										"reptiles",
										"small mammals",
										"trees",
										"vehicles 1",
										"vehicles 2"};
